/*
 * Generated by XDoclet - Do not edit!
 */
package br.com.bovinos.services;

/**
 * Remote interface for BovinosOperacoesSP.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface BovinosOperacoesSP
   extends javax.ejb.EJBObject
{

   public void implantar( br.com.sankhya.ws.ServiceContext ctx )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void retImplantar( br.com.sankhya.ws.ServiceContext ctx )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void iniCobertura( br.com.sankhya.ws.ServiceContext ctx )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void descartarCobertura( br.com.sankhya.ws.ServiceContext ctx )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void confirmaDiag( br.com.sankhya.ws.ServiceContext ctx )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void confirmaNascimento( br.com.sankhya.ws.ServiceContext ctx )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void salvaNascimento( br.com.sankhya.ws.ServiceContext ctx )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void buscaNascimento( br.com.sankhya.ws.ServiceContext ctx )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void insereItemMovAniNota( br.com.sankhya.ws.ServiceContext ctx )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void ocorrenciaAnimal( br.com.sankhya.ws.ServiceContext ctx )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void deleteItensMovAni( br.com.sankhya.ws.ServiceContext ctx )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void desativarBrinco( br.com.sankhya.ws.ServiceContext ctx )
      throws java.lang.Exception, java.rmi.RemoteException;

}
