/*
 * Generated by XDoclet - Do not edit!
 */
package br.com.bovinos.services;

/**
 * Home interface for BovinosOperacoesSP.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface BovinosOperacoesSPHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/BovinosOperacoesSP";
   public static final String JNDI_NAME="br/com/bovinos/services/BovinosOperacoesSP";

   public br.com.bovinos.services.BovinosOperacoesSP create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
