/*
 * Generated by XDoclet - Do not edit!
 */
package br.com.bovinos.services;

/**
 * Remote interface for ControleOperacoesSP.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface ControleOperacoesSP
   extends javax.ejb.EJBObject
{

   public void registraItemConf( br.com.sankhya.ws.ServiceContext ctx )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void validaBrincoJaConf( br.com.sankhya.ws.ServiceContext ctx )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void alteraStatusConf( br.com.sankhya.ws.ServiceContext ctx )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void registraPesoConferencia( br.com.sankhya.ws.ServiceContext ctx )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void registraCadNovoConferencia( br.com.sankhya.ws.ServiceContext ctx )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void registraAnimalRat( br.com.sankhya.ws.ServiceContext ctx )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void geraTGFNUM( br.com.sankhya.ws.ServiceContext ctx )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void estornarRateioFinAnimal( br.com.sankhya.ws.ServiceContext ctx )
      throws java.lang.Exception, java.rmi.RemoteException;

}
