/*
 * Generated by XDoclet - Do not edit!
 */
package br.com.bovinos.services;

/**
 * Home interface for ControleOperacoesSP.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface ControleOperacoesSPHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ControleOperacoesSP";
   public static final String JNDI_NAME="br/com/bovinos/services/ControleOperacoesSP";

   public br.com.bovinos.services.ControleOperacoesSP create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
